[project]
name = "brickgpt-demo"
version = "0.1.0"
description = "Official BrickGPT Gradio demo"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bpy",
    "brickgpt",
    "gradio",
]

[tool.uv.sources]
brickgpt = { git = "https://github.com/AvaLovelace1/BrickGPT.git" }
